apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        resources: {}
        image: elasticsearch:7.17.15
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          valueFrom:
            configMapKeyRef:
              name: geonetwork-config
              key: discovery.type
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: geonetwork-config
              key: ES_JAVA_OPTS
        - name: network.host
          valueFrom:
            configMapKeyRef:
              name: geonetwork-config
              key: network.host
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-data

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200